// Auto-generated schema registry — bundled as inline data (no readFileSync)
// Regenerate: pnpm build (runs scripts/generate-schemas.ts)
export const SCHEMA_REGISTRY: Record<string, Record<string, unknown>> = {
  "accessibility.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "$id": "schemas/accessibility.input.json", "type": "object", "required": ["mode"], "properties": {"mode": {"type": "string", "enum": ["crawl", "session"], "description": "crawl: score pages against WCAG criteria. session: return checklist for agent to enforce."}, "level": {"type": "string", "enum": ["A", "AA", "AAA"], "default": "AA", "description": "WCAG conformance level to evaluate against"}, "pages": {"type": "array", "minItems": 1, "maxItems": 100, "items": {"type": "object", "required": ["url", "html"], "properties": {"url": {"type": "string", "description": "URL of the page being audited"}, "html": {"type": "string", "description": "HTML content of the page"}}}}, "locale": {"type": "string", "default": "en", "description": "BCP 47 locale code"}}, "allOf": [{"if": {"properties": {"mode": {"const": "crawl"}}}, "then": {"required": ["pages"]}}, {"if": {"properties": {"mode": {"const": "session"}}}, "then": {"required": ["level"]}}], "additionalProperties": false},
  "accessibility.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "$id": "schemas/accessibility.output.json", "type": "object", "properties": {"mode": {"type": "string", "enum": ["crawl", "session"]}, "level": {"type": "string", "enum": ["A", "AA", "AAA"]}, "ranking": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "aggregate_score": {"type": "integer", "minimum": 0, "maximum": 100}, "automated": {"type": "integer", "minimum": 0}, "manual": {"type": "integer", "minimum": 0}, "total": {"type": "integer", "minimum": 0}, "criteria": {"type": "array"}, "heuristic": {"type": "boolean"}}}}, "site_aggregate": {"type": "integer", "minimum": 0, "maximum": 100, "description": "Average score across all pages"}, "checklist": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "title": {"type": "string"}, "level": {"type": "string", "enum": ["A", "AA", "AAA"]}, "principle": {"type": "string", "enum": ["perceivable", "operable", "understandable", "robust"]}, "requirement": {"type": "string"}, "implementation": {"type": "string"}}}}, "session_notice": {"type": "string"}, "criteria_count": {"type": "object", "properties": {"total": {"type": "integer"}, "A": {"type": "integer"}, "AA": {"type": "integer"}, "AAA": {"type": "integer"}}}, "summary": {"type": "string"}}, "additionalProperties": false},
  "age-inclusive-design.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["flow_description"], "properties": {"flow_description": {"type": "string"}, "age_groups": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/age-inclusive-design.input.json"},
  "age-inclusive-design.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["recommendations"], "properties": {"recommendations": {"type": "array", "items": {"type": "string"}}, "access_notes": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/age-inclusive-design.output.json"},
  "cognitive-accessibility.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["content"], "properties": {"content": {"type": "string"}, "target_context": {"type": "string", "default": "general digital interface", "description": "Optional context about the target audience or use case (e.g. 'healthcare patients', 'elderly users')"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/cognitive-accessibility.input.json"},
  "cognitive-accessibility.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["findings", "recommendations"], "properties": {"findings": {"type": "array", "items": {"type": "string"}}, "recommendations": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/cognitive-accessibility.output.json"},
  "conflict-de-escalation.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["situation"], "properties": {"situation": {"type": "string"}, "intensity": {"type": "string", "enum": ["low", "medium", "high"], "default": "medium"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/conflict-de-escalation.input.json"},
  "conflict-de-escalation.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["plan"], "properties": {"plan": {"type": "array", "items": {"type": "string"}}, "risk_notes": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/conflict-de-escalation.output.json"},
  "cultural-sensitivity.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["message", "audience"], "properties": {"message": {"type": "string"}, "audience": {"type": "string"}, "region": {"type": "string", "default": "global", "description": "Optional geographic region for more specific cultural context"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/cultural-sensitivity.input.json"},
  "cultural-sensitivity.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["adapted_message", "notes"], "properties": {"adapted_message": {"type": "string"}, "notes": {"type": "array", "items": {"type": "string"}}, "uncertainty": {"type": "string"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/cultural-sensitivity.output.json"},
  "depression-sensitive-content.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["text"], "properties": {"text": {"type": "string"}, "mode": {"type": "string", "enum": ["audit", "rewrite"], "default": "rewrite"}, "domain": {"type": "string", "default": "general", "description": "Optional domain context (e.g. 'healthcare', 'social media')"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/depression-sensitive-content.input.json"},
  "depression-sensitive-content.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["result", "safety_flags"], "properties": {"result": {"type": "string"}, "safety_flags": {"type": "array", "items": {"type": "string"}}, "pattern_count": {"type": "integer"}, "review_recommended": {"type": "boolean"}, "crisis_resources": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/depression-sensitive-content.output.json"},
  "empathetic-communication.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["message"], "properties": {"message": {"type": "string"}, "tone": {"type": "string", "enum": ["neutral", "warm", "formal"], "default": "warm"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/empathetic-communication.input.json"},
  "empathetic-communication.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["reframed_message"], "properties": {"reframed_message": {"type": "string"}, "rationale": {"type": "array", "items": {"type": "string"}}, "escalation_guidance": {"type": "array", "items": {"type": "string"}, "description": "Optional escalation steps when emotional content suggests higher risk"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/empathetic-communication.output.json"},
  "neurodiversity-aware-design.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["ui_description"], "properties": {"ui_description": {"type": "string"}, "focus": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/neurodiversity-aware-design.input.json"},
  "neurodiversity-aware-design.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["recommendations"], "properties": {"recommendations": {"type": "array", "items": {"type": "string"}}, "tradeoffs": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/neurodiversity-aware-design.output.json"},
  "supportive-conversation.input.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["message", "risk_level"], "properties": {"message": {"type": "string"}, "risk_level": {"type": "string", "enum": ["low", "medium", "high"]}, "locale": {"type": "string", "default": "en"}, "support_mode": {"type": "string", "enum": ["general", "presence", "practical", "reflection"], "default": "general"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/supportive-conversation.input.json"},
  "supportive-conversation.output.json": {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object", "required": ["reply", "escalation_guidance"], "properties": {"reply": {"type": "string"}, "escalation_guidance": {"type": "array", "items": {"type": "string"}}, "boundaries_notice": {"type": "string", "description": "Safety boundary notice for this action"}, "care_notes": {"type": "array", "items": {"type": "string"}, "description": "Care notes specific to grief support modes (presence, practical, reflection)"}}, "additionalProperties": false, "$id": "https://humanity4ai.github.io/project_human/schemas/supportive-conversation.output.json"},
};
